// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiEy45Sp3e3zgn51tqvViTBI2teidzovI',
    appId: '1:800566568532:web:b10d5a3a88b72d30b2efc1',
    messagingSenderId: '800566568532',
    projectId: 'social-learning-new',
    authDomain: 'social-learning-new.firebaseapp.com',
    storageBucket: 'social-learning-new.appspot.com',
    measurementId: 'G-0Y6XW387P4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXOWJO3Dw-KOHjNTu4XXNmGvBmuOPRbFo',
    appId: '1:800566568532:android:164782f8550844aab2efc1',
    messagingSenderId: '800566568532',
    projectId: 'social-learning-new',
    storageBucket: 'social-learning-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgIEBHW781Xk2eTME7A_AK6PRLnfJTZ3o',
    appId: '1:800566568532:ios:ae7dbcac53cee3ddb2efc1',
    messagingSenderId: '800566568532',
    projectId: 'social-learning-new',
    storageBucket: 'social-learning-new.appspot.com',
    iosClientId: '800566568532-2p7au82nv2cqnvdhlsujg8h7ai7pv4fl.apps.googleusercontent.com',
    iosBundleId: 'com.example.newProject',
  );

}